language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements_dev.txt
script:
  - python setup.py test
after_success: coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel --universal"
  skip_existing: true
  user:
    secure: "uLRrg7zDFF+tinHOQdN3WHw0ljtSxnPZXRziiJ64HIiIauWaBtjOLoyoNU6f5zPGcaxrrAsD6RxuYgVawFTGGiqMyy1qVx/6XGiA69xQ8OtR5nlV6WOgnzTXGg4gLn1F+/SrZMpOa54LtwfPw9NAKjsD1VAGNM4OHUU3NmQqoNk0eCmTzCEJr5uAZ9aZ8Q5E4H6RAuoNWHT5sl0K26t42NbhYGccRQzSdrYHHbL/p7Fg8zOY7MfNU4WoUA/OWDlHXr+syoaA/wAU95J88IIWS0RN8JSCQMrjjuH3HwQuCmso0OhA+DWFck6TZm4Y4URmmr0blmxNtuQmZD8ds8mP7pfv/KOoTuIpCUbfacL6BlXkSqF9dNTIocwuGRxN19Y22Z6bltqcwaBRmRsifLeWhfT3bCR2J2uR8huJzS59zSJN3u4KPUHY2A3E5PJ63z58haJ0ovOMGAz9v8iOnQAMuOg8ydb0tNBo2SaMRY0inGuj4F/zjVOTb5gWZQOG+R6ZpxHgf1vPbGMq7zMk72bfMX70WV/h4g68e9VXi51pE6C9qL7zT3TxGkMqUumsRSdH0i+HlLiLNgarMoz92pQpl3JpKusmPhQIdceiFtnV+08sX/M1kJmJZXg8ZQ1DxVboFUETtFwTUGiZ+p8KskXA4nrfAULFaNIVGXqE1JjHHow="
  password:
    secure: "aPpP36yJUfXEtTZbFk4cGwwrwlM/zl8BctWj1GhwLo7BTGLJ7pb3o0zUcM4MmHtWPt9hZDRaWfeZqEwRSxmFlPVnaiU94rHzoxtS3nP+bbJrePG3TIcUMoJRvWvXTrLETod/KqWe41ydDm7WhSt0jsXtmdsISX2KOjl9rkf7qUCmhl5vQ1glBLASTb384cZKXcxe7pzhDCxcGP7AJkhVz1mx9VvTOFdRBZgNk2yrFizoyCCcmC3hGiwdW0qn5f3GT517JEQZaTNyB+YAmUVfRPJoE1yaJEUt6vTTnZ3DtviZ8wWCkaLs7TkCYqVa8GgqTDb345KAojpvlLxzZjYUiL5c8LDlm2DUw+FONsRz7k6U8cRxKqJp8wQ+xT8hwtDRLoiRgR3q7BeHuNVsuN08HmkXWXw0iWhYF9HivbU1bUd77Xrv4MM2qlVRhFTGlsbrB5ZK1PsjAyv1rD9YLypPa6s8vMbLQR6HYo+8RkFS+LMyMGtK6dnG7IOZNE+6XM79aTfLYW1aQgIRrEaA9wK0n7uOi5rrW53/TO3XRBm2c5KeNSHFkDwPb0tFoti8daSNcwUujbo+QuO9aSrcYzNNO0OOSLRZ3AaEyiKmETw8wBaCdtLg1rwXgCKItR0ZYBZkANK9rDG8y/AQ4KKtJVAqTn8wj8RieIItoBtcDkw2bXk="
  on:
    tags: true
