dist: xenial
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install tox-travis
script: tox
after_success: coveralls
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel --universal"
  skip_existing: true
  user:
    secure: lvoLZsX/NAjWSZUxL4pOgrzM8CwmMTUp34Fjoi1YSybJrYl43ji+ga+RbTBjJIMLklytNqxtT3xT5sXRqySoAFzX43nL/+vsy1j+0Pbf+aCtzUwCp8xINBm3cnAcdVhIzk3pEcSCgE5S2DGPHM7Gmb0SRQjag9VLs+fyNXpC1qF1vr+20zJubMelet7ls+Ze9jTyJsaCTnlB1q1QWqntjSdjpimtCeoEHAClliHIeXpkLuViJFHirCLjniOPOFFyryrzpvPpM6KoL6BIwL5J3dr5DzcPgEw9kBruxg6EUrzPROIeeaL1P+hljm4u7t71cbEAy28+QbeO1AP8pwk3Dk7VxjxmEosb2a9Bv5N6r8g+snuDIE2gyUV5lzZpkM2jDzIAoX7UIboSrAwdKLIqKmWj2ASzUVr4d1Jd9QK0ubJkfANdtaF+uBOjeh1aaaqw7phmMFSr2H/qcYJgh9KA3v00T5mVZg6H49KBfDYVcmAAlYYOwPn51tCghiN6mYqDVUxunPoo7VZTEQupuBU47slHP/5jyS8nFLtrq2m/adD0f2nFENRoDcAO0eMQHyTVNnY7qqRnoJW5x/0mHbJXYRWF8VF5oA/S/xviOQpp5ncU/ucD/zvkUm2IljIOuDzNKi4ZuEu5ub5JnHU+MdCpdO/ozLOdaLjTmHq496FPYpw=
  password:
    secure: RoJYLVoCbZt0eAUTsllIPDWX05dnpFWVyprGjGSWlAIbwMoqfEv2cQFJFOls8+8uQ8l+7NA9M5o8I4vSw5v1/RB1Z25m3JAhQ7LuGsnTSEAQMjr/8LSjDpJ5pjijuvNdLUFyd45rZZxkkkDogNSH1RFSeQI8yQbz302SMbUJE1qeP1/dykNjnlO/xFvUJjBAS907rXg6h9xLbCcmcbbvCXGg5roVi1uL2Vrya5FF2+tTzuT0TPXoZ8TrGOBQ5GYKNfIjrvdeME9JKsFvyT+t19QQOQJV20AfhZdPXjL2/uHLYfkdcYrmGO2Dmbs0g9quRzTa5H9LdEEPg2fx0Zydq6JNZ3RggkhGGkTOEUZsvp7Qoms5ZaKQ2nlk5iInHlhbgN2tVI9831+6cahlwZARc1p+TEjqCeEKKa4mik6uLqHins9cck6GnBI8or06tFa0GYCzo0DI9HmOpgbVHCDbZalxKzJvDoiyhCENy6gBfQalo1zHQMDJW9BQrtfpKfyPGI2ixyz89FB+w7Yhc7tFf05//cxw9n0bEAPcLLw+fAlAsEwmvMS/8Q7QtNXgSJLJo0x708k9IWw5lEAYMvSTqh0e6iSAWCINC0mJK33bTsUfXuonfiW+OYQlLTLe8Gvt0B1yA6HnZ0WG4gR0PyQTiwPDN4nVUxBgP5Yd3+GRJFE=
  on:
    tags: true
